'use client'

import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'
export default function CastingPage(){const [calls,setCalls]=useState<any[]>([]);const [user,setUser]=useState<any>(null);const [applied,setApplied]=useState<string[]>([]);const [message,setMessage]=useState('');
 async function load(){const {data:{user}}=await supabase.auth.getUser();setUser(user);const {data,error}=await supabase.from('casting_calls').select('*').eq('status','open').order('created_at',{ascending:false});if(error)setMessage(error.message);setCalls(data||[]);if(user){const {data:a}=await supabase.from('applications').select('casting_call_id').eq('actor_user_id',user.id);setApplied((a||[]).map(x=>x.casting_call_id))}}
 useEffect(()=>{void load()},[])
 async function apply(id:string){if(!user){setMessage('Please sign in before applying.');return}const {error}=await supabase.from('applications').insert({casting_call_id:id,actor_user_id:user.id,status:'applied'});if(error)setMessage(error.message);else{setMessage('Application submitted successfully.');await load()}}
 return <main className="payment-page container"><a className="back-link" href="/">← Where Talent Meets Film</a><div className="payment-header"><div><div className="eyebrow">Open opportunities</div><h1>Casting calls.</h1><p>Explore active roles and apply directly to production teams.</p></div><div className="actions"><a className="btn secondary" href="/account">My account</a><a className="btn secondary" href="/notifications">Notifications</a></div></div>{message&&<div className="info-box"><p>{message}</p></div>}<div className="payment-layout"><section>{calls.length===0?<div className="payment-card"><h2>No open casting calls yet.</h2><p className="muted">Production teams can publish opportunities here as they become available.</p></div>:calls.map(c=><article className="payment-card" key={c.id}><div className="eyebrow">{c.city}, {c.country}</div><h2>{c.title}</h2><p><strong>{c.project_name}</strong> · {c.role_name}</p><p>{c.description}</p><div className="tags">{(c.skills||[]).map((s:string)=><span className="tag" key={s}>{s}</span>)}{(c.languages||[]).map((s:string)=><span className="tag" key={s}>{s}</span>)}</div><p className="muted">Experience: {c.experience_level}{c.age_min||c.age_max?` · Age ${c.age_min||'18'}–${c.age_max||'+'}`:''}</p>{c.audition_requirement&&<div className="info-box"><strong>Audition</strong><p>{c.audition_requirement}</p></div>}<button className="btn primary" disabled={applied.includes(c.id)} onClick={()=>apply(c.id)}>{applied.includes(c.id)?'Application submitted':'Apply for this role →'}</button></article>)}</section></div></main>}
